item {
  id: 1
  name: 'fixed_wing_aircraft'
}
item {
  id: 2
  name: 'small_aircraft'
}
item {
  id: 3
  name: 'cargo_plane'
}
item {
  id: 4
  name: 'helicopter'
}
item {
  id: 5
  name: 'passenger_vehicle'
}
item {
  id: 6
  name: 'small_car'
}
item {
  id: 7
  name: 'bus'
}
item {
  id: 8
  name: 'pickup_truck'
}
item {
  id: 9
  name: 'utility_truck'
}
item {
  id: 10
  name: 'truck'
}
item {
  id: 11
  name: 'cargo_truck'
}
item {
  id: 12
  name: 'truck_w_box'
}
item {
  id: 13
  name: 'truck_tractor'
}
item {
  id: 14
  name: 'trailer'
}
item {
  id: 15
  name: 'truck_w_flatbed'
}
item {
  id: 16
  name: 'truck_w_liquid'
}
item {
  id: 17
  name: 'crane_truck'
}
item {
  id: 18
  name: 'railway_vehicle'
}
item {
  id: 19
  name: 'passenger_car'
}
item {
  id: 20
  name: 'cargo_car'
}
item {
  id: 21
  name: 'flat_car'
}
item {
  id: 22
  name: 'tank_car'
}
item {
  id: 23
  name: 'locomotive'
}
item {
  id: 24
  name: 'maritime_vessel'
}
item {
  id: 25
  name: 'motorboat'
}
item {
  id: 26
  name: 'sailboat'
}
item {
  id: 27
  name: 'tugboat'
}
item {
  id: 28
  name: 'barge'
}
item {
  id: 29
  name: 'fishing_vessel'
}
item {
  id: 30
  name: 'ferry'
}
item {
  id: 31
  name: 'yacht'
}
item {
  id: 32
  name: 'container_ship'
}
item {
  id: 33
  name: 'oil_tanker'
}
item {
  id: 34
  name: 'engineering_vehicle'
}
item {
  id: 35
  name: 'tower_crane'
}
item {
  id: 36
  name: 'container_crane'
}
item {
  id: 37
  name: 'reach_stacker'
}
item {
  id: 38
  name: 'straddle_carrier'
}
item {
  id: 39
  name: 'mobile_crane'
}
item {
  id: 40
  name: 'dump_truck'
}
item {
  id: 41
  name: 'haul_truck'
}
item {
  id: 42
  name: 'scraper_tractor'
}
item {
  id: 43
  name: 'front_loader_bulldozer'
}
item {
  id: 44
  name: 'excavator'
}
item {
  id: 45
  name: 'cement_mixer'
}
item {
  id: 46
  name: 'ground_grader'
}
item {
  id: 47
  name: 'hut_tent'
}
item {
  id: 48
  name: 'shed'
}
item {
  id: 49
  name: 'building'
}
item {
  id: 50
  name: 'aircraft_hangar'
}
item {
  id: 51
  name: 'damaged_building'
}
item {
  id: 52
  name: 'facility'
}
item {
  id: 53
  name: 'construction_site'
}
item {
  id: 54
  name: 'vehicle_lot'
}
item {
  id: 55
  name: 'helipad'
}
item {
  id: 56
  name: 'storage_tank'
}
item {
  id: 57
  name: 'shipping_container_lot'
}
item {
  id: 58
  name: 'shipping_container'
}
item {
  id: 59
  name: 'pylon'
}
item {
  id: 60
  name: 'tower'
}
item {
  id: 61
  name: 'dontcare'
}
